version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    restart: always
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env

volumes:
  postgres-data:
